version: "3"

services:
    api:
        container_name: api
        build: 
            context: ./dotnet
            dockerfile: ./Dockerfile
        image: api:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - C:\Users\hannes\Desktop\aster:/data/dem
            - c:\temp\tiles:/data/cache
        environment:
            - DEM_DATA=/data/dem
            - CACHE_FOLDER=/data/cache